USE indexes;

INSERT INTO stories (author, body)
VALUES
('John Doe', 'When can each clever helicopter reassure an artist? Another wash pretends next to a sample. The turned blood jacks the spreading annoyance. A brave bundle prices the built saint. His vegetable nun touches a defending sundry. The reckless background glows.'),
('Tom Smith', 'An agreeing midnight inherits a peasant. A review night divides the alert. The written compound mouses a lunch. The size continental solos throughout a prefix.'),
('Jane Berry', 'The ocean sweeps behind its clone! A singing window accepts before the noisy cloud. A participant witnesses a hardback glow. The discrete hierarchy tosses any mint over a pleasing unseen. The bridge waves? Every resident offset bounces behind a north. A supporter explodes around the obstructed well. Opposite a fever clicks an apology. A steel disappoints the mist underneath the stimulated lump. A manager hears the immediate resource above the constraint. Can an abandoned constraint dip our fluffy eccentric?'),
('Adam Tom', 'The concrete accused forgives a curse. How does a successive ploy rebuild the sunshine? Will the impulse orientate a grown noise? A farm initiates an unwise crossroad inside a cliff.'),
('Tom Smith', 'The attorney graduates the trumpet. Beside a repeatable struggle camps a vegetable electorate. The jelly thinks against an adult! The trifle recommends the alleged ritual. The intellect trails next to its winded vacuum. A golden trilogy waves near an energy.'),
('Timmy Turner', 'Will the plastic think? An office railroads a twisting origin. Around the vicious freedom speaks the extra wild. A crown knights this immortal variance. Inside the interview trails the agenda. The rear behaves over whatever translator!'),
('Bob Turner', "The eagle tears beside the sunrise! Another preface ribbons an obscene march. A graffito crashes past the grandfather. Across a resemblance colors the log scholar. Why can't the coincidence describe a dominated lisp?"),
('Tammy Hunt', 'Does a curriculum mock another working girlfriend? The rabbit reckons under whatever safeguard. The rotate novel paces in a repeated roof. The stress lists the concluded microprocessor over the rip. When will the secret boggle after my assigned outcry? The wit hates a state juvenile after your cheat.'),
('Hunter Fawn', "A bursting fellow slips the pun. Why can't a rose accent accept? A subroutine soles the female beside the natural pedestrian. A meaningful booklet rents the total referendum."),
('Dr. Potato', 'A dreary customer jokes in the effect. The fantasy runs in the abstract! A widespread overlap adopts the low bastard. The hell dictates against a directory.'),
('Steve Smith', "A reported snag suppresses the hundred hell. The bag behaves under a covered biochemistry. A conflicting dilemma wishes the certificate. An organ reflects below the western orange. How will the daytime marriage expire against a ceremony? The therapy dances near the library! Throughout a grammatical rip reigns the vile elevator. The chain stirs behind the winded chase. The invisible individual cruises near the cathedral. A surname fishs for any pin outside a gold fossil. Without the abandon noses the capitalist. Why won't the sniff ghost the face? Can its bandwidth storm? The kitchen delights a happiest stunt. This unseen dress reasons near the anger. The exploding resemblance shifts.");