CC = gcc
CFLAGS = -g -Wall

all: Problem1 Problem2 Problem3

Problem1: Problem1.c
	$(CC) $(CFLAGS) $(INCLUDE1) -o $@.o $<

Problem2: Problem2.c
	$(CC) $(CFLAGS) $(INCLUDE1) -o $@.o $<

Problem3: Problem3.c
	$(CC) $(CFLAGS) $(INCLUDE1) -o $@.o $<

clean:
	-rm -f *.o *~ *core* 
